from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'start{CMD_INDEX}'
        self.MirrorCommand = f'makemecum{CMD_INDEX}'
        self.UnzipMirrorCommand = f'spillmycum{CMD_INDEX}'
        self.ZipMirrorCommand = f'fillmewithcum{CMD_INDEX}'
        self.CancelMirror = f'stopmasturbating{CMD_INDEX}'
        self.CancelAllCommand = f'stopcumming{CMD_INDEX}'
        self.ListCommand = f'listmycum{CMD_INDEX}'
        self.SearchCommand = f'lookforcumstash{CMD_INDEX}'
        self.StatusCommand = f'watchmecum{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'peoplewhocanwatchmecum{CMD_INDEX}'
        self.AuthorizeCommand = f'allowtoseemecumming{CMD_INDEX}'
        self.UnAuthorizeCommand = f'disallowtoseemecumming{CMD_INDEX}'
        self.AddSudoCommand = f'bemysugardaddy{CMD_INDEX}'
        self.RmSudoCommand = f'dontbemysugardaddy{CMD_INDEX}'
        self.PingCommand = f'cum{CMD_INDEX}'
        self.RestartCommand = f'recum{CMD_INDEX}'
        self.StatsCommand = f'cummingvitals{CMD_INDEX}'
        self.HelpCommand = f'howtomakememcum{CMD_INDEX}'
        self.LogCommand = f'log{CMD_INDEX}'
        self.CloneCommand = f'rapidmasturbation{CMD_INDEX}'
        self.CountCommand = f'count{CMD_INDEX}'
        self.WatchCommand = f'cumonyoutube{CMD_INDEX}'
        self.ZipWatchCommand = f'fillyoutubecum{CMD_INDEX}'
        self.QbMirrorCommand = f'makemecumlikeapro{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'spillmycumlikeapro{CMD_INDEX}'
        self.QbZipMirrorCommand = f'fillmewithcumlikeapro{CMD_INDEX}'
        self.DeleteCommand = f'del{CMD_INDEX}'
        self.ShellCommand = f'shell{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelp{CMD_INDEX}'
        self.LeechSetCommand = f'leechset{CMD_INDEX}'
        self.SetThumbCommand = f'cummingpicture{CMD_INDEX}'
        self.LeechCommand = f'cumontelegram{CMD_INDEX}'
        self.UnzipLeechCommand = f'spillmycumontelegram{CMD_INDEX}'
        self.ZipLeechCommand = f'fillmewithcumontelegram{CMD_INDEX}'
        self.QbLeechCommand = f'cumontelegramlikeapro{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'spillmycumontelegramlikeapro{CMD_INDEX}'
        self.QbZipLeechCommand = f'fillmewithcumontelegramlikeapro{CMD_INDEX}'
        self.LeechWatchCommand = f'watchmecumontelegram{CMD_INDEX}'
        self.LeechZipWatchCommand = f'watchmegettingfilledwithcum{CMD_INDEX}'
        self.BtSelectCommand = f'btsel{CMD_INDEX}'
        self.RssListCommand = f'rsslist{CMD_INDEX}'
        self.RssGetCommand = f'rssget{CMD_INDEX}'
        self.RssSubCommand = f'rsssub{CMD_INDEX}'
        self.RssUnSubCommand = f'rssunsub{CMD_INDEX}'
        self.RssSettingsCommand = f'rssset{CMD_INDEX}'
        self.EvalCommand = f'eval{CMD_INDEX}'
        self.ExecCommand = f'exec{CMD_INDEX}'
        self.ClearLocalsCommand = f'clearlocals{CMD_INDEX}'

BotCommands = _BotCommands()
